---
title: "VTparity - data clean"
output: html_notebook
---
  
  Initial packages

```{r}
#rm(list=ls(all=TRUE))
library(ape)
library(treeplyr)
library(rotl)
library(castor)
library(geiger)
library(phytools)
library(phylolm)
dat <- read.csv("../datasets/vtparity.csv")
getwd()
```


```{r}
#Read taxonomy table back in
ott_table <- readRDS(file="../output/ott_table_data.rds")
tax_table <- readRDS("../output/ott_tax_table.rds")
td_tree <- readRDS("../output/matched_tree_ott.rds")
tree <- td_tree$phy
tree$tip.label <- gsub(" ", "_", td_tree$dat$ott_name)
```

# fish data clean
```{r}
dat <- read.csv("../datasets/vtparity.csv")
fishdat <- read.csv("../datasets/final_vtparity_fishdata_complete.csv")

#fishdat$AaM[which(fishdat$AaM == "1.5-2")] <- "1.75"
#fishdat$mass[which(fishdat$mass == "2.0-89.0")] <- "89.0"
unique(fishdat$mass)
fishdat$AaM <- as.numeric(fishdat$AaM)
fishdat$mass <- as.numeric(fishdat$mass)
fishdat <- mutate(fishdat, birth.mass=NA)
.fishdat <- dplyr::select(fishdat, colnames(dat))
ordind <- match(.fishdat$species, dat$species)
newdat <- dat
for(i in 1:nrow(.fishdat)){
  tofill <- which(is.na(dat[ordind[i], ]) & !is.na(.fishdat[i, ]))
  newdat[ordind[i], tofill] <- .fishdat[i, tofill]
}
newdat$genspec <- NA # Create genspec
index <- match(ott_table$search_string, gsub(" ", "_", newdat$species)) #match ott_table to data table
drop <- which(is.na(index)) #Some failed, record these
newdat$genspec[index[-drop]] <- ott_table$unique_name[-drop] # Give the ott names to genspec

ndat <- filter(newdat, !is.na(genspec)) # Keep only the ones that worked
ndat$genspec <- gsub(" ", "_", ndat$genspec) #underscores
td <- make.treedata(tree, ndat)#match tree and data. 
saveRDS(td, "../output/chordatedata_matched_new_ott.rds")
```

```{r}
library(dplyr)

lens <- read.csv("../datasets/VTparity_length_mass.csv")
#taking the mean for each species
length(lens$Species)
g <- aggregate(cbind(lens$a, lens$b), by = list(lens$Species), mean)
colnames(g) <- c("Species", "a", "b")
shark_lens <- read.csv("../datasets/Shark.VTparity.data.csv")
shark_lens <- dplyr::select(shark_lens, c(4,15,16))
colnames(shark_lens) <- c("Species",  "a","b")
lens_attempt <- merge(lens, shark_lens, by = "Species")
colnames(lens_attempt) <- c("Species","X", "a1","b1","a","b")

# changing values when they are different
ind <- which(lens_attempt$a1 != lens_attempt$a)
change <- lens_attempt[ind,]
lens_shark <- data.frame(lens$Species, lens$a, lens$b)
colnames(lens_shark) <- c("species","a","b")
#old_dat <- read.csv("../datasets/vtparity.csv")
dat <- read.csv("../datasets/vtparity.csv")
dat <- data.frame(dat)

#merging the two 
#full_dat <- merge(dat, lens_shark, by = "species", all.x = T)

g <- data.frame(g)
names(g) <- c("species", "a","b")

# combo of both datasets 
get <- plyr::join(g, dat, by = 'species', type = "full")

#get_mass <- mutate(get, mass_est = a * (svl^b))

#converting 
get$a <- ifelse(get$a < 0, yes = exp(get$a), get$a)

transformed_dat <- saveRDS(get, file = "../output/transformed_dat.RDS")

get_mass_con <- mutate(get, logSVL = log(svl,10), logMass = log(mass))

get_mass_jo <- mutate(get_mass_con, logEstMass = log((a*svl)^b))#(b * logSVL + log((a),10))* 1/log(exp(1),10))

#saving 
saveRDS(get_mass_jo, file = "../output/NB_massEst.RDS")
mass_est <- readRDS("../output/NB_massEst.RDS")

lm1 <- lm(mass_est$logEstMass / 3 ~  mass_est$logSVL)
#main plot
plot(mass_est$logSVL, mass_est$logEstMass / 3, pch = 16, cex = 1.3, col = "red", 
     main = "log(estMass)/3 and log10SVL", xlab = "log10SVL", ylab = " log(estMass) / 3")
abline(lm1)

# dropping based on residual
lm1.res <- (resid(lm1))
plot(lm1.res)
res_ind <- (which((lm1.res) < -2))
r <- as.data.frame(res_ind)
q <- as.numeric(rownames(r))
res_ind <- c(r$res_ind, q)
# outliers based on the residuals, not sure whether the reptiles should be dropped
res_out <- mass_est[res_ind,]

# dropped dataset 
mass_est <- mass_est[-res_ind, ]
saveRDS(mass_est, file = "../output/NB_massEst_NoOutliers.RDS")

par(mfrow = c(2,1))
hist(get_mass_jo$a)
hist(res_out$a)


# things to be dropped based on svl and estMass
ind_out <- which(get_mass_jo$logEstMass < 0 & get_mass_jo$logSVL > 2.5)
eye_out <- get_mass_jo[ind_out,]

par(mfrow = c(2,1))
hist(eye_out$a)
hist(res_out$a)

```


# II. Load in matched tree and data. 
  
```{r}
td0 <- readRDS("../output/chordatedata_matched_new_ott.rds")
newmass <- readRDS("../output/NB_massEst_NoOutliers.RDS")
mergemass <- left_join(td0$dat, newmass)
mergemass <- mutate(mergemass, lnSize=ifelse(is.na(logMass)==TRUE, logEstMass/3, logMass/3))
mergemass$lnSize[mergemass$class=="Actinopterygii" & !is.na(mergemass$lnSize)] <- mergemass$lnSize[mergemass$class=="Actinopterygii" & !is.na(mergemass$lnSize)] - log(10)
mergemass$lnSize[mergemass$class=="Actinopterygii" & is.na(mergemass$lnSize)] <- log((0.007 * mergemass$svl[mergemass$class=="Actinopterygii" & is.na(mergemass$lnSize)])^3.0904)/3 #(3.0904 * log(mergemass$svl[mergemass$class=="Actinopterygii" & is.na(mergemass$lnSize)], 10) + log(0.007,10))/3 *  1/log(exp(1),10)
mergemass$species <- td0$phy$tip.label
testudines_allometry <- read.csv("../datasets/turtles_AllometryofSexualSizeDimorphism.csv")
testudines_allometry$genspec <- paste(testudines_allometry$Genus, testudines_allometry$Species, sep="_")

#For species with female mass, set female mass directly
female_turt_mass <- setNames(testudines_allometry$F.Mass..g., testudines_allometry$genspec)
mergemass$mass[mergemass$order=="Testudines"] <- unname(female_turt_mass[mergemass$species[mergemass$order=="Testudines"]])
mergemass$lnSize[mergemass$order=="Testudines" & is.na(mergemass$lnSize)] <- log(mergemass$mass[mergemass$order=="Testudines"])/3

#For species with only SCL, calculate allometry
y <- log(c(testudines_allometry$M.Mass..g., testudines_allometry$F.Mass..g.))
x <- log(c(testudines_allometry$M.SCL..mm., testudines_allometry$F.SCL..mm.))
lm1 <- lm(y~x, na.action = "na.omit")
mergemass$lnSize[mergemass$order=="Testudines" & is.na(mergemass$lnSize)] <- (lm1$coef[1] + lm1$coef[2]*log(mergemass$svl[mergemass$order=="Testudines" & is.na(mergemass$lnSize)]))/3

td <- make.treedata(td0$phy, mergemass)

plot(td$dat$logSVL, td$dat$lnSize)
points(td$dat$logSVL[td$dat$order=="Testudines"], td$dat$lnSize[td$dat$order=="Testudines"], col="red")
 
 
.td <- filter(td, class=="Actinopterygii")
plot(.td[['logSVL']], .td[['lnSize']])
plot(td[['logSVL']], td[['lnSize']], pch=21, bg=(td$dat$class=="Actinopterygii")+1)
plot(td[['logSVL']], td[['lnSize']], pch=21, bg=(td$phy$tip.label=="Catlocarpio_siamensis")+1)


saveRDS(td, "../output/chordatedata_matched_estSizeComplete.rds")
```

