---
title: "VTparity - ternary analysis"
output: html_notebook
---
  
  # Initial packages
  
```{r}
#rm(list=ls(all=TRUE))
library(ape)
library(treeplyr)
library(rotl)
library(castor)
library(geiger)
library(phytools)
library(phylolm)
library(Ternary)
dat <- read.csv("../datasets/vtparity.csv")
getwd()
```

```{r}
td <- readRDS("../output/chordatedata_matched_estSizeComplete.rds")
```

#Ternary plots
```{r}

terntd <- td %>% filter(!is.na(juvMort), !is.na(adMort), !is.na(lnSize), !is.na(repmode)) %>% mutate(scSize = lnSize/(abs(diff(range(lnSize,na.rm=TRUE)))/4), scadMort=adMort/(abs(diff(range(adMort,na.rm=TRUE)))/4), scjMort=juvMort/(abs(diff(range(juvMort,na.rm=TRUE)))/4)) %>% mutate(scSize=scSize-min(scSize, na.rm=TRUE), scadMort=scadMort-min(scadMort, na.rm=TRUE), scjMort=scjMort-min(scjMort, na.rm=TRUE)) %>% mutate(trAdMort = scadMort/(scadMort+scjMort+scSize), trJMort = scjMort/(scadMort+scjMort+scSize), trSize = scSize/(scadMort+scjMort+scSize))
terntd$dat$species <- terntd$phy$tip.label
terntd <-filter(terntd, !is.na(trJMort), !is.na(trAdMort), !is.na(trSize)) %>% select(order, class, family,species, trAdMort, trJMort, trSize, repmode, AdTerr, Terr)
Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Class")
TernaryPoints(terntd$dat[,5:7], pch=21, cex=0.35, bg=terntd$dat$class, col=terntd$dat$class)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Reproductive Mode")
TernaryPoints(terntd$dat[,5:7], pch=21, cex=0.35, bg=terntd$dat$repmode+1, col=terntd$dat$repmode+1)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Adult Terrestrial")
TernaryPoints(terntd$dat[,5:7], pch=21, cex=0.35, bg=terntd$dat$AdTerr+1, col=terntd$dat$AdTerr+1)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Juv Terrestrial")
TernaryPoints(terntd$dat[,5:7], pch=21, cex=0.35, bg=terntd$dat$Terr+1, col=terntd$dat$Terr+1)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Sharks")
.terntd <- filter(terntd, order=="Sharks")
TernaryPoints(.terntd$dat[,5:7], pch=21, cex=0.35, bg=.terntd$dat$repmode+1, col=.terntd$dat$repmode+1)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Reptilia")
.terntd <- filter(terntd, class=="Reptilia")
TernaryPoints(.terntd$dat[,5:7], pch=21, cex=0.35, bg=.terntd$dat$repmode+1, col=.terntd$dat$repmode+1)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Aves")
.terntd <- filter(terntd, class=="Aves")
TernaryPoints(.terntd$dat[,5:7], pch=21, cex=0.35, bg=.terntd$dat$repmode+1, col=.terntd$dat$repmode+1)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Amphibia")
.terntd <- filter(terntd, class=="Amphibia")
TernaryPoints(.terntd$dat[,5:7], pch=21, cex=0.35, bg=.terntd$dat$repmode+1, col=.terntd$dat$repmode+1)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Actinopterygii")
.terntd <- filter(terntd, class=="Actinopterygii")
TernaryPoints(.terntd$dat[,5:7], pch=21, cex=0.35, bg=.terntd$dat$repmode+1, col=.terntd$dat$repmode+1)

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Mammalia")
.terntd <- filter(terntd, class=="Mammalia")
TernaryPoints(.terntd$dat[,5:7], pch=21, cex=0.35, bg=.terntd$dat$repmode+1, col=.terntd$dat$repmode+1)


Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Not mammals or birds")
.terntd <- filter(terntd, !class %in% c("Mammalia", "Aves"))
TernaryPoints(.terntd$dat[,5:7], pch=21, cex=0.35, bg=.terntd$dat$repmode+1, col=.terntd$dat$repmode+1)


#plot(terntd$dat$trAdMort, terntd$dat$trJMort)


```

## Now fit to discrete ternary plot data
```{r}
library(Ternary)
library(MCMCpack)
library(combinat)
library(dplyr)

dat <- dplyr::select(terntd$dat, 5,6,7)

bins <- 3

combos <- combinat::combn(rep(1:bins,3), 3) ## Create all combinations of values 1:bins
sums <- apply(combos, 2, sum) #Sum the 3 values for the 3 traits
combos <- combos[,sums %in% c(bins+2, bins+1)] #Only retain those that sum to bins+2 and bins+1 (fit in the triangle)
cells <- t(combos[,!duplicated(apply(combos, 2,paste, collapse=""))]) #remove duplicated bin combinations
colnames(cells) <- c("A", "B", "C") #label traits
cells <- cells[order(cells[,3],(bins+1)-cells[,1],(bins+1)-cells[,2], decreasing=TRUE),] #reorder the cells to be prettier
cellnames <- apply(cells, 1, paste, collapse="") #Give the cells a state label  
ddat <- apply(dat, 2, cut,breaks=seq(0,1, length.out=bins+1), labels=1:bins) #Find where the data falls in the state space
ddat <- match(apply(ddat, 1, paste, collapse=""), cellnames) #match the data's state to the state label
terntd <- mutate(terntd, ddat=ddat) 


Ternary::TernaryPlot(alab="A", blab="B", clab="C", grid.lines = 3) #Plot with points labeled by their numeric state value (values with more than two digits won't show up right)
ssq <- seq(0, 1, length.out=bins+4)[c(2,4,6)]
midcells <- cbind(ssq[cells[,1]], ssq[cells[,2]], ssq[cells[,3]])
for(i in 1:nrow(midcells)){
  midcells[i,] <- midcells[i,]/sum(midcells[i,])
}
colnames(midcells) <- colnames(cells)
TernaryPoints(midcells, pch=as.character(1:9))
#TernaryPoints(dat, pch=as.character(ddat)) 

Q <- as.matrix(dist(cells))
Q[Q!=1] <- 0
Q
```

```{r}
library(castor)
.terntd <- filter(terntd, !is.na(ddat))
ERfit <- castor::fit_mk(.terntd$phy, 9, tip_states=.terntd[['ddat']], rate_model=Q)
ERfit


```

```{r}
## Viviparity
.terntd <- dplyr::mutate(.terntd, ddatpm = ddat+repmode*9) %>% filter(!class %in% c("Mammalia", "Aves"))
DM1 <- DM2 <- diag(9)
diag(DM1) <- 2
diag(DM2) <- 3

Qpm0.ER <- rbind(cbind(Q, DM1), cbind(DM1, Q))
Qpm0.Asym <- rbind(cbind(Q, DM1), cbind(DM2, Q))
rownames(Qpm0.ER) <- colnames(Qpm0.ER) <- 1:18
rownames(Qpm0.Asym) <- colnames(Qpm0.Asym) <- 1:18
Fit.pm0.ER <- castor::fit_mk(.terntd$phy, 18, tip_states=.terntd[['ddatpm']], rate_model=Qpm0.ER)
Fit.pm0.Asym <- castor::fit_mk(.terntd$phy, 18, tip_states=.terntd[['ddatpm']], rate_model=Qpm0.Asym)
Fit.pm0.ER
Fit.pm0.Asym

```


```{r}
Qpm1235.ER <- Qpm0.ER
Qpm1235.Asym <- Qpm0.Asym

pmRates <- cbind(c(1,2,3,5), c(1,2,3,5)+nrow(Q))
for(i in 1:nrow(pmRates)){
  Qpm1235.ER[pmRates[i,1], pmRates[i,2]]<- Qpm1235.ER[pmRates[i,2], pmRates[i,1]] <- max(Qpm0.ER)+1
}

pmRates <- cbind(c(1,2,3,5), c(1,2,3,5)+nrow(Q))
for(i in 1:nrow(pmRates)){
  Qpm1235.Asym[pmRates[i,1], pmRates[i,2]]<- max(Qpm0.Asym)+1
  Qpm1235.Asym[pmRates[i,2], pmRates[i,1]]<- max(Qpm0.Asym)+2
}



Qpm1235.ER
Qpm1235.Asym

Fit.pm1235.ER <- castor::fit_mk(.terntd$phy, 18, tip_states=.terntd[['ddatpm']], rate_model=Qpm1235.ER)
Fit.pm1235.Asym <- castor::fit_mk(.terntd$phy, 18, tip_states=.terntd[['ddatpm']], rate_model=Qpm1235.Asym)
Fit.pm1235.ER$loglikelihood
Fit.pm1235.Asym$loglikelihood

```

```{r}
DM3 <- DM4 <- diag(9)
diag(DM3) <- 1:9
diag(DM4) <- 10:18
Qpm.ARD <- rbind(cbind(Q, DM3), cbind(DM4,Q))
colnames(Qpm.ARD) <- rownames(Qpm.ARD) <- 1:18
Fit.pm.ARD <- castor::fit_mk(.terntd$phy, 18, tip_states=.terntd[['ddatpm']], rate_model=Qpm.ARD)

```



```{r}
cat("\nAIC ER no parity equal across regions\n")
2* max(Qpm0.ER) - 2*Fit.pm0.ER$loglikelihood
cat("\nAIC Asym no parity equal across regions\n")
2* max(Qpm0.Asym) - 2*Fit.pm0.Asym$loglikelihood
cat("\nAIC ER viviparous increased in 1235\n")
2* max(Qpm1235.ER) - 2*Fit.pm1235.ER$loglikelihood
cat("\nAIC Asym viviparous increased in 1235\n")
2* max(Qpm1235.Asym) - 2*Fit.pm1235.Asym$loglikelihood

```

```{r}

Ternary::TernaryPlot(alab="Adult Mortality", blab="Juv Mortality", clab="Body Size", main="Not mammals or birds", grid.lines = 3)
.terntd <- filter(terntd, !class %in% c("Mammalia", "Aves"))
TernaryPoints(.terntd$dat[,5:7], pch=21, cex=0.35, bg=.terntd$dat$repmode+1, col=.terntd$dat$repmode+1)
TernaryPoints(midcells, pch=as.character(1:9), col="red", cex=1.25)
```
